export const Countries = ['Austria', 'Australia', 'Belgium', 'Brazil', 'Canada', 'Switzerland', 'Germany', 'Spain', 'France', 'United Kingdom', 'India', 'Italy', 'Mexico', 'Netherlands', 'New Zealand', 'Poland', 'Russia', 'Singapore', 'United States', 'South Africa'];

export const SupportedCountries = ["at", "au", "be", "br", "ca", "ch", "de", "es", "fr", "gb", "in", "it", "mx", "nl", "nz", "pl", "ru", "sg", "us", "za"];

export const CountryMap = {'Austria' : 'at', 'Australia': 'au', 'Belgium' : 'be', 'Brazil' : 'br', 'Canada' : 'ca', 'Switzerland' : 'ch', 'Germany' : 'de', 'Spain' : 'es', 'France' : 'fr', 'United Kingdom' : 'gb', 'India' : 'in', 'Italy' : 'it', 'Mexico' : 'mx', 'Netherlands' : 'nl', 'New Zealand' : 'nz', 'Poland' : 'pl', 'Russia' : 'ru', 'Singapore' : 'sg', 'United States' : 'us', 'South Africa' : 'za'};

export const JobLabel = ["Accounting & Finance Jobs",
"IT Jobs",
"Sales Jobs",
"Customer Services Jobs",
"Engineering Jobs",
"HR & Recruitment Jobs",
"Healthcare & Nursing Jobs",
"Hospitality & Catering Jobs",
"PR, Advertising & Marketing Jobs",
"Logistics & Warehouse Jobs",
"Teaching Jobs",
"Trade & Construction Jobs",
"Admin Jobs",
"Legal Jobs",
"Creative & Design Jobs",
"Graduate Jobs",
"Retail Jobs",
"Consultancy Jobs",
"Manufacturing Jobs",
"Scientific & QA Jobs",
"Social work Jobs",
"Travel Jobs",
"Energy, Oil & Gas Jobs",
"Property Jobs",
"Charity & Voluntary Jobs",
"Domestic help & Cleaning Jobs",
"Maintenance Jobs",
"Part time Jobs",
"Other/General Jobs",
"Unknown",
"Empleos en contabilidad y finanzas",
"Empleos en informática",
"Empleos en ventas",
"Empleos en atención al cliente",
"Empleos en ingeniería",
"Empleos en recursos humanos",
"Empleos en sanidad y salud",
"Empleos en hosteleria y restauración",
"Empleos en marketing, publicidad y relaciones públicas",
"Empleos en logística y almacén",
"Empleos en educación",
"Empleos en construcción",
"Empleos en administración",
"Empleos en legal",
"Empleos en diseño y artes gráficas",
"Empleos para recién egresados",
"Empleos en tiendas",
"Empleos en consultoría",
"Empleos en fabricación y manufactura",
"Empleos en ciencias y control de calidad",
"Empleos en servicios sociales",
"Empleos en turismo",
"Empleos en energía, petroleo y gas",
"Empleos en inmobiliarias",
"Voluntariados",
"Empleos de limpieza",
"Empleos de mantenimiento",
"Empleos de medio tiempo",
"Otros empleos",
"Księgowość i finanse",
"IT",
"Sprzedaż",
"Obsługa klienta",
"Inżynieria",
"HR i rekrutacja",
"Służba zdrowia",
"Gastronomia",
"PR, reklama, marketing",
"Logistyka i magazyn",
"Nauczanie",
"Budownictwo",
"Administracja",
"Prawo",
"Design i praca twórcza",
"Studenci i absolwenci",
"Handel detaliczny",
"Doradztwo",
"Produkcja",
"Praca naukowa i QA",
"Praca społeczna",
"Turystyka",
"Energetyka i surowce",
"Nieruchomości",
"Wolontariat i charytatywna",
"Pomoce domowe",
"Naprawy",
"Na pół etatu",
"Inna/ogólna"];

export const JobLabelTagMap = {
"Accounting & Finance Jobs": "accounting-finance-jobs",
"IT Jobs": "it-jobs",
"Sales Jobs": "sales-jobs",
"Customer Services Jobs": "customer-services-jobs",
"Engineering Jobs": "engineering-jobs",
"HR & Recruitment Jobs": "hr-jobs",
"Healthcare & Nursing Jobs": "healthcare-nursing-jobs",
"Hospitality & Catering Jobs": "hospitality-catering-jobs",
"PR, Advertising & Marketing Jobs": "pr-advertising-marketing-jobs",
"Logistics & Warehouse Jobs": "logistics-warehouse-jobs",
"Teaching Jobs": "teaching-jobs",
"Trade & Construction Jobs": "trade-construction-jobs",
"Admin Jobs": "admin-jobs",
"Legal Jobs": "legal-jobs",
"Creative & Design Jobs": "creative-design-jobs",
"Graduate Jobs": "graduate-jobs",
"Retail Jobs": "retail-jobs",
"Consultancy Jobs": "consultancy-jobs",
"Manufacturing Jobs": "manufacturing-jobs",
"Scientific & QA Jobs": "scientific-qa-jobs",
"Social work Jobs": "social-work-jobs",
"Travel Jobs": "travel-jobs",
"Energy, Oil & Gas Jobs": "energy-oil-gas-jobs",
"Property Jobs": "property-jobs",
"Charity & Voluntary Jobs": "charity-voluntary-jobs",
"Domestic help & Cleaning Jobs": "domestic-help-cleaning-jobs",
"Maintenance Jobs": "maintenance-jobs",
"Part time Jobs": "part-time-jobs",
"Other/General Jobs": "other-general-jobs",
"Unknown": "unknown",
"Empleos en contabilidad y finanzas": "accounting-finance-jobs",
"Empleos en informática": "it-jobs",
"Empleos en ventas": "sales-jobs",
"Empleos en atención al cliente": "customer-services-jobs",
"Empleos en ingeniería": "engineering-jobs",
"Empleos en recursos humanos": "hr-jobs",
"Empleos en sanidad y salud": "healthcare-nursing-jobs",
"Empleos en hosteleria y restauración": "hospitality-catering-jobs",
"Empleos en marketing, publicidad y relaciones públicas": "pr-advertising-marketing-jobs",
"Empleos en logística y almacén": "logistics-warehouse-jobs",
"Empleos en educación": "teaching-jobs",
"Empleos en construcción": "trade-construction-jobs",
"Empleos en administración": "admin-jobs",
"Empleos en legal": "legal-jobs",
"Empleos en diseño y artes gráficas": "creative-design-jobs",
"Empleos para recién egresados": "graduate-jobs",
"Empleos en tiendas": "retail-jobs",
"Empleos en consultoría": "consultancy-jobs",
"Empleos en fabricación y manufactura": "manufacturing-jobs",
"Empleos en ciencias y control de calidad": "scientific-qa-jobs",
"Empleos en servicios sociales": "social-work-jobs",
"Empleos en turismo": "travel-jobs",
"Empleos en energía, petroleo y gas": "energy-oil-gas-jobs",
"Empleos en inmobiliarias": "property-jobs",
"Voluntariados": "charity-voluntary-jobs",
"Empleos de limpieza": "domestic-help-cleaning-jobs",
"Empleos de mantenimiento": "maintenance-jobs",
"Empleos de medio tiempo": "part-time-jobs",
"Otros empleos": "other-general-jobs",
"Księgowość i finanse": "accounting-finance-jobs",
"IT": "it-jobs",
"Sprzedaż": "sales-jobs",
"Obsługa klienta": "customer-services-jobs",
"Inżynieria": "engineering-jobs",
"HR i rekrutacja": "hr-jobs",
"Służba zdrowia": "healthcare-nursing-jobs",
"Gastronomia": "hospitality-catering-jobs",
"PR, reklama, marketing": "pr-advertising-marketing-jobs",
"Logistyka i magazyn": "logistics-warehouse-jobs",
"Nauczanie": "teaching-jobs",
"Budownictwo": "trade-construction-jobs",
"Administracja": "admin-jobs",
"Prawo": "legal-jobs",
"Design i praca twórcza": "creative-design-jobs",
"Studenci i absolwenci": "graduate-jobs",
"Handel detaliczny": "retail-jobs",
"Doradztwo": "consultancy-jobs",
"Produkcja": "manufacturing-jobs",
"Praca naukowa i QA": "scientific-qa-jobs",
"Praca społeczna": "social-work-jobs",
"Turystyka": "travel-jobs",
"Energetyka i surowce": "energy-oil-gas-jobs",
"Nieruchomości": "property-jobs",
"Wolontariat i charytatywna": "charity-voluntary-jobs",
"Pomoce domowe": "domestic-help-cleaning-jobs",
"Naprawy": "maintenance-jobs",
"Na pół etatu": "part-time-jobs",
"Inna/ogólna": "other-general-jobs"
}